# -*- coding: utf-8 -*-
"""python basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WZgZKAkJqpmcquVh5r9cbZ9VusnWN0zK

**What is python?**

1.Python is powerful programming language.
2.Specially used in data science,machine learning to solve daily life real-time problems and
providing the solutions.
3.Python is a high-level,intrepeted,interactive and object oriented scripting langauge.*italicized text*

History of Python language:
1. Python was developed by "Guido Van Rossum" in late 1980's in National Research Institute
for Mathematics and Computer Science in Netherlands.
2. Python was derived from many other languages includingABC,Modulo3,C,C++,Algol=68,SmallTalk,Unix shell and other scripting languages.

**why python?**

1.Easy to understand
2.Easy syntax
3.Beginner friendly
4.Supports multiple libraries
5.Supports OOP's

**Application of python**

1.Web applications

2.Desktop applications

3.Database applications

4.Web scraping

5.Wen mapping

6.Data analysis

7.Interactive web visualization

8.Computer vision and image processing etc.
"""

#code to print all the keywords present in python
import keyword
print(keyword.kwlist)
a=len(keyword.kwlist)
print(a)

"""**Indentation in python**

1.In C,C++,the indentation is specified by using the flowerbrackdets{}.

2.In python,indentation is done by 4 white spaces or tab.

**Python comments**

In python we have 2 types of comments such as follow:

1.single line comment(specified using single or double quotes).

2.multi line comment(specified using doc sring).
"""

#single line comment--->shows the single line comment.
print('hello my dear friends')

"""
multi line comment
how are you all
have a nice day guys
"""
print('hello CSE people')

"""**PYTHON VARIABLES**

1.Variables are nothing but reserved memory locations to store values.

2.When we create a varaible ,automatically some space in memory isreserved.

3.Based on the data types the interpreter allocates the memory.

4.Varaible can take any data type such as integer,float numbers,strings etc.
"""

#exampl1:
#here 3 variables have been created and stored the values as shown below
a=50
b=50
c=a+b
print(c)
#example 2 on strings
x='hello'
x

"""**Python data types**

1.Integer data type

2.Float point numbers

3.Strings data type

4.Boolean data type

**Python Data Structure**

1.In python we have four types of data structures

2.These data structures are very useful and important while working with advance topics such
as machine learning ,data science.

1.List

2.Tuple

3.Dictionary

4.Sets

**1.LISTS IN PYTHON**

*List is a python data structure

*it is a combination of any data type.

*enclosed within [] and separated by commas(,).

*list is sequence of values called items or elements.

*list is similar arrays.

*list mutable.

*list is indexible.
"""

#Creating a list with constructor()
a=([1,2,3,4,5])
b=([2.4,7.0,6.8])
c=(['hello','students'])
print(a)
print(b)
print(c)

type(a)

#creating list with heterogenous data:
a=(["hello",8,9,20,77])
a

#create list using range function:
L=list(range(0,6))
print(L)

#creating a list without constructor():
days=['monday','tuesday','wednesday','thursday','friday','saturday','sunday']
days

#accesing list items using index values:
days[1]

#negative indexing:
#creating a list without constructor():
days=['monday','tuesday','wednesday','thursday','friday','saturday','sunday']
days[-1]

days[:]

#list slicing:
days[1:4]

#list slicing with step size:
days=['monday','tuesday','wednesday','thursday','friday','saturday','sunday']
days[1:4:2]

"""**LIST BUILT-IN FUNCTION**

"""

#example1:
s=['monday','tuesday','wednesday','thursday','friday','saturday','sunday']
len(s)

numbers=[1,2,3,4,5,6,7,8]
max(numbers)

numbers=[1,2,3,4,5,6,7,8]
min(numbers)

numbers=[1,2,3,4,5,6,7,8]
sum(numbers)

import random
numbers=[1,2,3,4,5,6,7,8]
random.shuffle(numbers)
print(numbers)

"""**List Operators**"""

#examples on operator:
x=[1,2,3]
y=[4,5,6]
z=x+y
print(z)

a=[10,20]
b=3*a
print(b)

days=['monday','tuesday','wednesday','thursday','friday','saturday','sunday']
'wednesday' in days

days=['monday','tuesday','wednesday','thursday','friday','saturday','sunday']
'wednesday' not in days

a='Saihan'
b='Saihan'
a is b

a='Saihan'
b='Yusuf'
a is b

days=['monday','tuesday','wednesday','thursday','friday','saturday','sunday']
del[days[1]]
days

"""**List Methods**"""

a=['a','b','c','d']
print(a)
a.append('e')
print(a)

list=['red','orange','pink','black']
print(list)
list.clear()
print(list)

nums=[1,2,3,4,1,4,1,7,8,1]
print(nums)
nums.count(1)

list_1=[1,2,3,4]
print(list_1)
list_2=list_1.copy()
print(list_2)

A=[1,3,2,4,5]
B=[5,6,7,3,6]
print(A)
print(B)
A.extend(B)
print(A)

"""**PYTHON TUPLES**

1.Tuple is another important data structures present in python.

2.Allow multiple data types.

3.Enclosed () and separated by commas(,).

4.Tuples are not mutable

5.Tuples are indexible

6.Tuples are ordered
"""

#creating tuple with single element:
a=(5,)
print(a)
print(type(a))

#creating tuple with integers
a=(1,2,3,4,5)
print(a)

#creating tuple with float numbers
b=(6.5,5.9,2.0)
print(b)

#creating tuple with strings
c=('one','two','three')
c

#creating tuple multiple data types
mix=('hello',708,66.8,1,2)
mix

#accessing items of tuple
a=(1,2,3,4,'hello')
print(a[4])

"""**3.PYTHON DICTIONARY**

1.Dictionaries are used to store the values in key-value pair.

2.It's a combination of keys and values

3.Elements are accessed based on the keys

4.It is ordered,mutable,and dont allow duplicate elements.

5.Enclosed within {} with key value pair


"""

#create a dictionary
a={
'name':'Saihan',
'age':20,
'education':'BCA'
}
print(a)

len(a)

type(a)

y=a.keys()
y

z=a.values()
z

x=a.items()
x

clear(a)

"""**4.Python Sets**

1.Sets are used to store multiple items in a single variable.

2.Sets are enclosed withing {}.

3.Sets are unordered,not mutable and unidexible.

4.Sets items are unchangable but we can remove and add new items.
"""

#Example:
seta={1,2,3,4}
print(seta)

# 3 duplicates not allowed
set={1,2,3,4,5,6,7,1,1}
set

len(set)

type(set)

"""**Set Methods**"""

set1 = {"apple", "banana", "cherry"}

set1.add("orange")

print(set1)

set2 = {"apple", "banana", "cherry"}
tropical = {"pineapple", "mango", "papaya"}

set2.update(tropical)

print(set2)

set1 = {"apple", "banana", "cherry"}

set1.clear()

print(set1)

"""**Python Operators**

1.Arthematic operators

2.Comparison operators

3.Logical operators

4.Assignment operators

5.Special operators

6.Identity operators

7.Membership operators

"""

print((6 + 3) - (6 + 3))

print(100 + 5 * 3)

print(5 + 4 - 7 + 3)

"""**Python Functions**"""

def add():
  a=2
  b=3
  sum=a+b
  return sum
add()
print(add())